// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	DUPLICATETRANSFER ErrorCode = "DUPLICATE_TRANSFER"
	FUNDNOTFOUND      ErrorCode = "FUND_NOT_FOUND"
	INSUFFICIENTUNITS ErrorCode = "INSUFFICIENT_UNITS"
	INTERNALERROR     ErrorCode = "INTERNAL_ERROR"
	INVALIDFUND       ErrorCode = "INVALID_FUND"
	INVALIDREQUEST    ErrorCode = "INVALID_REQUEST"
	OWNERNOTFOUND     ErrorCode = "OWNER_NOT_FOUND"
	SELFTRANSFER      ErrorCode = "SELF_TRANSFER"
)

// CapTable Paginated cap table for a fund
type CapTable struct {
	// Entries Cap table entries for the current page
	Entries []CapTableEntry `json:"entries"`

	// FundId The fund this cap table belongs to
	FundId openapi_types.UUID `json:"fundId"`

	// Limit Maximum entries per page
	Limit int `json:"limit"`

	// Offset Number of entries skipped
	Offset int `json:"offset"`

	// Total Total number of entries in the cap table
	Total int `json:"total"`
}

// CapTableEntry A single entry in the cap table representing an owner's stake
type CapTableEntry struct {
	// AcquiredAt Timestamp when the ownership was first acquired
	AcquiredAt time.Time `json:"acquiredAt"`

	// OwnerName Name of the unit holder (no leading/trailing whitespace)
	OwnerName string `json:"ownerName"`

	// Percentage Percentage of total fund units owned
	Percentage float64 `json:"percentage"`

	// Units Number of units owned
	Units int `json:"units"`
}

// CreateFundRequest Request body for creating a new fund
type CreateFundRequest struct {
	// InitialOwner Name of the initial owner who receives all units (no leading/trailing whitespace)
	InitialOwner string `json:"initialOwner"`

	// Name Name of the fund (no leading/trailing whitespace)
	Name string `json:"name"`

	// TotalUnits Total number of ownership units in the fund
	TotalUnits int `json:"totalUnits"`
}

// CreateTransferRequest Request body for creating a new transfer
type CreateTransferRequest struct {
	// FromOwner Name of the sender (must exist in cap table, no leading/trailing whitespace)
	FromOwner string `json:"fromOwner"`

	// IdempotencyKey Client-generated key for deduplication. If provided, subsequent requests with the same key will return the original transfer.
	IdempotencyKey *openapi_types.UUID `json:"idempotencyKey,omitempty"`

	// ToOwner Name of the recipient (no leading/trailing whitespace)
	ToOwner string `json:"toOwner"`

	// Units Number of units to transfer (must not exceed sender's holdings)
	Units int `json:"units"`
}

// Error Structured error response
type Error struct {
	// Code Machine-readable error code
	Code ErrorCode `json:"code"`

	// Details Additional context about the error
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// ErrorCode Machine-readable error code
type ErrorCode string

// Fund An investment fund with ownership units
type Fund struct {
	// CreatedAt Timestamp when the fund was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier for the fund
	Id openapi_types.UUID `json:"id"`

	// Name Name of the fund (no leading/trailing whitespace)
	Name string `json:"name"`

	// TotalUnits Total number of ownership units in the fund
	TotalUnits int `json:"totalUnits"`
}

// Transfer A record of units transferred between owners
type Transfer struct {
	// FromOwner Name of the sender (no leading/trailing whitespace)
	FromOwner string `json:"fromOwner"`

	// FundId The fund the transfer belongs to
	FundId openapi_types.UUID `json:"fundId"`

	// Id Unique identifier for the transfer
	Id openapi_types.UUID `json:"id"`

	// ToOwner Name of the recipient (no leading/trailing whitespace)
	ToOwner string `json:"toOwner"`

	// TransferredAt Timestamp when the transfer was executed
	TransferredAt time.Time `json:"transferredAt"`

	// Units Number of units transferred
	Units int `json:"units"`
}

// FundId defines model for FundId.
type FundId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest Structured error response
type BadRequest = Error

// DuplicateTransfer Structured error response
type DuplicateTransfer = Error

// FundNotFound Structured error response
type FundNotFound = Error

// InternalError Structured error response
type InternalError = Error

// TransferBadRequest Structured error response
type TransferBadRequest = Error

// TransferNotFound Structured error response
type TransferNotFound = Error

// GetCapTableParams defines parameters for GetCapTable.
type GetCapTableParams struct {
	// Limit Maximum number of entries to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of entries to skip
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateFundJSONRequestBody defines body for CreateFund for application/json ContentType.
type CreateFundJSONRequestBody = CreateFundRequest

// CreateTransferJSONRequestBody defines body for CreateTransfer for application/json ContentType.
type CreateTransferJSONRequestBody = CreateTransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all funds
	// (GET /funds)
	ListFunds(w http.ResponseWriter, r *http.Request)
	// Create a new fund
	// (POST /funds)
	CreateFund(w http.ResponseWriter, r *http.Request)
	// Get a fund by ID
	// (GET /funds/{fundId})
	GetFund(w http.ResponseWriter, r *http.Request, fundId FundId)
	// Get cap table for a fund
	// (GET /funds/{fundId}/cap-table)
	GetCapTable(w http.ResponseWriter, r *http.Request, fundId FundId, params GetCapTableParams)
	// List transfers for a fund
	// (GET /funds/{fundId}/transfers)
	ListTransfers(w http.ResponseWriter, r *http.Request, fundId FundId)
	// Create a transfer
	// (POST /funds/{fundId}/transfers)
	CreateTransfer(w http.ResponseWriter, r *http.Request, fundId FundId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all funds
// (GET /funds)
func (_ Unimplemented) ListFunds(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new fund
// (POST /funds)
func (_ Unimplemented) CreateFund(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a fund by ID
// (GET /funds/{fundId})
func (_ Unimplemented) GetFund(w http.ResponseWriter, r *http.Request, fundId FundId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cap table for a fund
// (GET /funds/{fundId}/cap-table)
func (_ Unimplemented) GetCapTable(w http.ResponseWriter, r *http.Request, fundId FundId, params GetCapTableParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List transfers for a fund
// (GET /funds/{fundId}/transfers)
func (_ Unimplemented) ListTransfers(w http.ResponseWriter, r *http.Request, fundId FundId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a transfer
// (POST /funds/{fundId}/transfers)
func (_ Unimplemented) CreateTransfer(w http.ResponseWriter, r *http.Request, fundId FundId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListFunds operation middleware
func (siw *ServerInterfaceWrapper) ListFunds(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFunds(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFund operation middleware
func (siw *ServerInterfaceWrapper) CreateFund(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFund(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFund operation middleware
func (siw *ServerInterfaceWrapper) GetFund(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "fundId" -------------
	var fundId FundId

	err = runtime.BindStyledParameterWithOptions("simple", "fundId", chi.URLParam(r, "fundId"), &fundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fundId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFund(w, r, fundId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCapTable operation middleware
func (siw *ServerInterfaceWrapper) GetCapTable(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "fundId" -------------
	var fundId FundId

	err = runtime.BindStyledParameterWithOptions("simple", "fundId", chi.URLParam(r, "fundId"), &fundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fundId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCapTableParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCapTable(w, r, fundId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTransfers operation middleware
func (siw *ServerInterfaceWrapper) ListTransfers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "fundId" -------------
	var fundId FundId

	err = runtime.BindStyledParameterWithOptions("simple", "fundId", chi.URLParam(r, "fundId"), &fundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fundId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTransfers(w, r, fundId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTransfer operation middleware
func (siw *ServerInterfaceWrapper) CreateTransfer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "fundId" -------------
	var fundId FundId

	err = runtime.BindStyledParameterWithOptions("simple", "fundId", chi.URLParam(r, "fundId"), &fundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fundId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTransfer(w, r, fundId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/funds", wrapper.ListFunds)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/funds", wrapper.CreateFund)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/funds/{fundId}", wrapper.GetFund)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/funds/{fundId}/cap-table", wrapper.GetCapTable)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/funds/{fundId}/transfers", wrapper.ListTransfers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/funds/{fundId}/transfers", wrapper.CreateTransfer)
	})

	return r
}

type BadRequestJSONResponse Error

type DuplicateTransferJSONResponse Error

type FundNotFoundJSONResponse Error

type InternalErrorJSONResponse Error

type TransferBadRequestJSONResponse Error

type TransferNotFoundJSONResponse Error

type ListFundsRequestObject struct {
}

type ListFundsResponseObject interface {
	VisitListFundsResponse(w http.ResponseWriter) error
}

type ListFunds200JSONResponse []Fund

func (response ListFunds200JSONResponse) VisitListFundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListFunds500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListFunds500JSONResponse) VisitListFundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateFundRequestObject struct {
	Body *CreateFundJSONRequestBody
}

type CreateFundResponseObject interface {
	VisitCreateFundResponse(w http.ResponseWriter) error
}

type CreateFund201JSONResponse Fund

func (response CreateFund201JSONResponse) VisitCreateFundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateFund400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateFund400JSONResponse) VisitCreateFundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateFund500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateFund500JSONResponse) VisitCreateFundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFundRequestObject struct {
	FundId FundId `json:"fundId"`
}

type GetFundResponseObject interface {
	VisitGetFundResponse(w http.ResponseWriter) error
}

type GetFund200JSONResponse Fund

func (response GetFund200JSONResponse) VisitGetFundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFund400JSONResponse struct{ BadRequestJSONResponse }

func (response GetFund400JSONResponse) VisitGetFundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetFund404JSONResponse struct{ FundNotFoundJSONResponse }

func (response GetFund404JSONResponse) VisitGetFundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetFund500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetFund500JSONResponse) VisitGetFundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCapTableRequestObject struct {
	FundId FundId `json:"fundId"`
	Params GetCapTableParams
}

type GetCapTableResponseObject interface {
	VisitGetCapTableResponse(w http.ResponseWriter) error
}

type GetCapTable200JSONResponse CapTable

func (response GetCapTable200JSONResponse) VisitGetCapTableResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCapTable400JSONResponse struct{ BadRequestJSONResponse }

func (response GetCapTable400JSONResponse) VisitGetCapTableResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCapTable404JSONResponse struct{ FundNotFoundJSONResponse }

func (response GetCapTable404JSONResponse) VisitGetCapTableResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCapTable500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetCapTable500JSONResponse) VisitGetCapTableResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTransfersRequestObject struct {
	FundId FundId `json:"fundId"`
}

type ListTransfersResponseObject interface {
	VisitListTransfersResponse(w http.ResponseWriter) error
}

type ListTransfers200JSONResponse []Transfer

func (response ListTransfers200JSONResponse) VisitListTransfersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTransfers400JSONResponse struct{ BadRequestJSONResponse }

func (response ListTransfers400JSONResponse) VisitListTransfersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListTransfers404JSONResponse struct{ FundNotFoundJSONResponse }

func (response ListTransfers404JSONResponse) VisitListTransfersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListTransfers500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListTransfers500JSONResponse) VisitListTransfersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTransferRequestObject struct {
	FundId FundId `json:"fundId"`
	Body   *CreateTransferJSONRequestBody
}

type CreateTransferResponseObject interface {
	VisitCreateTransferResponse(w http.ResponseWriter) error
}

type CreateTransfer200JSONResponse Transfer

func (response CreateTransfer200JSONResponse) VisitCreateTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateTransfer201JSONResponse Transfer

func (response CreateTransfer201JSONResponse) VisitCreateTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTransfer400JSONResponse struct{ TransferBadRequestJSONResponse }

func (response CreateTransfer400JSONResponse) VisitCreateTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTransfer404JSONResponse struct{ TransferNotFoundJSONResponse }

func (response CreateTransfer404JSONResponse) VisitCreateTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateTransfer409JSONResponse struct{ DuplicateTransferJSONResponse }

func (response CreateTransfer409JSONResponse) VisitCreateTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateTransfer500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateTransfer500JSONResponse) VisitCreateTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all funds
	// (GET /funds)
	ListFunds(ctx context.Context, request ListFundsRequestObject) (ListFundsResponseObject, error)
	// Create a new fund
	// (POST /funds)
	CreateFund(ctx context.Context, request CreateFundRequestObject) (CreateFundResponseObject, error)
	// Get a fund by ID
	// (GET /funds/{fundId})
	GetFund(ctx context.Context, request GetFundRequestObject) (GetFundResponseObject, error)
	// Get cap table for a fund
	// (GET /funds/{fundId}/cap-table)
	GetCapTable(ctx context.Context, request GetCapTableRequestObject) (GetCapTableResponseObject, error)
	// List transfers for a fund
	// (GET /funds/{fundId}/transfers)
	ListTransfers(ctx context.Context, request ListTransfersRequestObject) (ListTransfersResponseObject, error)
	// Create a transfer
	// (POST /funds/{fundId}/transfers)
	CreateTransfer(ctx context.Context, request CreateTransferRequestObject) (CreateTransferResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListFunds operation middleware
func (sh *strictHandler) ListFunds(w http.ResponseWriter, r *http.Request) {
	var request ListFundsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFunds(ctx, request.(ListFundsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFunds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFundsResponseObject); ok {
		if err := validResponse.VisitListFundsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateFund operation middleware
func (sh *strictHandler) CreateFund(w http.ResponseWriter, r *http.Request) {
	var request CreateFundRequestObject

	var body CreateFundJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateFund(ctx, request.(CreateFundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateFund")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateFundResponseObject); ok {
		if err := validResponse.VisitCreateFundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFund operation middleware
func (sh *strictHandler) GetFund(w http.ResponseWriter, r *http.Request, fundId FundId) {
	var request GetFundRequestObject

	request.FundId = fundId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFund(ctx, request.(GetFundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFund")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFundResponseObject); ok {
		if err := validResponse.VisitGetFundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCapTable operation middleware
func (sh *strictHandler) GetCapTable(w http.ResponseWriter, r *http.Request, fundId FundId, params GetCapTableParams) {
	var request GetCapTableRequestObject

	request.FundId = fundId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCapTable(ctx, request.(GetCapTableRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCapTable")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCapTableResponseObject); ok {
		if err := validResponse.VisitGetCapTableResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTransfers operation middleware
func (sh *strictHandler) ListTransfers(w http.ResponseWriter, r *http.Request, fundId FundId) {
	var request ListTransfersRequestObject

	request.FundId = fundId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTransfers(ctx, request.(ListTransfersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTransfers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTransfersResponseObject); ok {
		if err := validResponse.VisitListTransfersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTransfer operation middleware
func (sh *strictHandler) CreateTransfer(w http.ResponseWriter, r *http.Request, fundId FundId) {
	var request CreateTransferRequestObject

	request.FundId = fundId

	var body CreateTransferJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTransfer(ctx, request.(CreateTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTransfer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTransferResponseObject); ok {
		if err := validResponse.VisitCreateTransferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
